services:
  api:
    image: thejasbh/fastapi:e2f5dd0
    container_name: fastapi.latest
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    restart: "no"
    volumes:
      - .:/ass2
  streamlit:
    image: thejasbh/streamlit:e2f5dd0
    container_name: streamlit.latest
    environment:
        PORT: 8501
    ports:
      - '8501:8501'
    restart: "no"
    volumes:
      - .:/ass2
    env_file:
      - ./.env
