name: fastapi-ci

on:  
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        id: commit
        uses: pr-mpt/actions-commit-hash@v2
      - 
        name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
      - 
        name: Install Requirements
        working-directory: ./pytest
        run: pip install -r requirements.txt
      - 
        name: Run tests
        working-directory: ./
        run: |
          python -m pytest pytest/file_url_generator_test_nexrad.py                                
          python -m pytest pytest/file_url_generator_test_geos.py                                

        # Running pytest
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # fetch from dockerhub
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # fetch from dockerhub
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./fastapi    # path to dockerfile
          # file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/labs_fastpi:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/labs_fastpi:${{ steps.commit.outputs.short }}
          # Change the container image "demo_fastapi_private"